# docker-compose.yml
version: '3.8'

services:
  cassandra:
    image: cassandra:4.1
    container_name: todolist_cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=TodoListCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  cassandra-init:
    image: cassandra:4.1
    container_name: todolist_cassandra_init
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./cmd/cassandra/init.cql:/init.cql
    entrypoint: [ "sh", "-c", "cqlsh cassandra -f /init.cql" ]
    environment:
      - CASSANDRA_CONTACT_POINT=cassandra
    restart: "no"

  app:
    build:
      context: .  # The build context is still the project root
      dockerfile: ./deploy/Dockerfile # Path to the Dockerfile relative to the context
    container_name: todolist_app
    ports:
      - "${SERVER_PORT:-7071}:${SERVER_PORT:-7071}"
    depends_on:
      cassandra: # App now only depends on Cassandra being healthy
        condition: service_healthy
    environment:
      CASSANDRA_HOSTS: "cassandra:9042"
      CASSANDRA_KEYSPACE: "todolist"
      SERVER_PORT: "${SERVER_PORT:-7071}"
    restart: unless-stopped

volumes:
  cassandra_data:
    driver: local